### PR TITLE
fix #1113 by adding 'dnu feeds list' command

### LINKED ISSUE #1113: Add nuget sources option
Currently trying to list the available NuGet sources using kpm blows up with an exception:

```
C:\Users\danroth27\Documents\Visual Studio 14\Projects\WebApplication7\src\WebApplication7>kpm sources
Specify --help for a list of available options and commands.
System.Exception: TODO: Error: unrecognized argument 'sources'
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```

### PR DESCRIPTION
**Pull request by anurse**
Fixes #1113

Add `dnu sources` command that lists active sources. It looks like this:

image

Disabled sources have `[Disabled]` next to them in yellow to identify them as disabled. I also tried to centralize some of the disjointed code we have to handle NuGet.config.

/cc @davidfowl @victorhurdugaci @troydai

### CODE REVIEW

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+        {
+            get
+            {
+                return TestUtils.GetRuntimeComponentsCombinations();
+            }
+        }
+
+        [Theory]
+        [MemberData(nameof(RuntimeComponents))]
+        public void DnuSources_ListsAllSources(string flavor, string os, string architecture)
```
Comment (anurse) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs]: I'm not 100% happy with this test. It's a little too brittle. I might see if I can tidy it up before pushing.

File: src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs [hunk 2]
```diff
@@ -63,7 +61,6 @@ public RestoreCommand(FrameworkName fallbackFramework)
 
         public List<FrameworkName> TargetFrameworks { get; set; } = new List<FrameworkName>();
         public FrameworkName FallbackFramework { get; set; }
-        public IMachineWideSettings MachineWideSettings { get; set; }
```
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs]: Nobody ever changes this value...

**Comment by victorhurdugaci** [comment]
Oh no! Please don't add `sources`. Change the name to something else. I already have a PR for `dnu source` which is for bringing source code :)

File: src/Microsoft.Framework.PackageManager/ConsoleCommands/SourcesConsoleCommand.cs [hunk 3]
```diff
@@ -0,0 +1,31 @@
+﻿// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using Microsoft.Framework.Runtime.Common.CommandLine;
+
+namespace Microsoft.Framework.PackageManager
+{
+    internal static class SourcesCommand
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/ConsoleCommands/SourcesConsoleCommand.cs]: `SourcesConsoleCommand`

**Comment by anurse** [comment]
Ok, but `sources` aligns with `nuget` so we might need to consider all the options...

**Comment by anurse** [comment]
I'm not sure I like `source` for the command you're building, it collides with the concept of package sources. I would propose something more like `dnu clone` for that command. It seems clearer what it does and frees this up.

I'm definitely open to renaming this though if people think that would be less confusing. We could do something like `dnu list-sources` (which does start to bring up potential collision with `dnu list`)

File: src/Microsoft.Framework.PackageManager/NuGetConfig.cs [hunk 4]
```diff
@@ -0,0 +1,44 @@
+﻿using System;
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/NuGetConfig.cs]: License.

File: src/Microsoft.Framework.PackageManager/NuGetConfig.cs [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+    internal class NuGetConfig
+    {
+        public NuGetConfig(ISettings settings, PackageSourceProvider sources)
+        {
+            Settings = settings;
+            Sources = sources;
+        }
+
+        public ISettings Settings { get; }
+        public IPackageSourceProvider Sources { get; }
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/NuGetConfig.cs]: Add a new line to separate the properties.

File: src/Microsoft.Framework.PackageManager/NuGetConfig.cs [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+        {
+            var settings = SettingsUtils.ReadSettings(
+                solutionDirectory, 
+                nugetConfigFile: null, 
+                fileSystem: fileSystem, 
+                machineWideSettings: new CommandLineMachineWideSettings());
+
+            // Recreate the source provider and credential provider
+            var sources = PackageSourceBuilder.CreateSourceProvider(settings);
+            //HttpClient.DefaultCredentialProvider = new SettingsCredentialProvider(new ConsoleCredentialProvider(Console), SourceProvider, Console);
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/NuGetConfig.cs]: Remove the commented code.

File: src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs [hunk 7]
```diff
@@ -912,12 +909,9 @@ void Display(string indent, IEnumerable<GraphNode> graphs)
...
         {
-            Settings = SettingsUtils.ReadSettings(solutionDirectory, NuGetConfigFile, FileSystem, MachineWideSettings);
-
-            // Recreate the source provider and credential provider
-            SourceProvider = PackageSourceBuilder.CreateSourceProvider(Settings);
-            //HttpClient.DefaultCredentialProvider = new SettingsCredentialProvider(new ConsoleCredentialProvider(Console), SourceProvider, Console);
-
+            var config = NuGetConfig.ForSolution(solutionDirectory, FileSystem);
+            Settings = config.Settings;
+            SourceProvider = config.Sources;
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs]: Why not just hold on to the instance of the config?

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+        public Reports Reports { get; set; }
+        public string TargetDirectory { get; set; }
+
+        public int Execute()
+        {
+            // Most of this code is from NuGet, just some refactoring for our system.
+            // Collect config
+            var config = NuGetConfig.ForSolution(TargetDirectory);
+
+            var sources = config.Sources.LoadPackageSources().ToList();
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Do we need the `ToList()`?

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+            {
+                Reports.Information.WriteLine("Registered Sources:");
+                // Iterate over the sources and report them
+                var nameLength = sources.Max(s => s.Name.Length);
+                for (int i = 0; i < sources.Count; i++)
+                {
+                    var source = sources[i];
+                    var indexNumber = i + 1;
+                    var enabledString = source.IsEnabled ? "" : " [Disabled]";
+                    var line = $"{indexNumber.ToString("0\\.").PadRight(3)} {source.Name.PadRight(nameLength)} {source.Source}{enabledString.Yellow().Bold()}";
```
Comment (troydai) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: I would suggest not to format it into a table. The URL source could be long. If user execute the command on a default 80 characters width console may cause it wrap the output.

Or maybe just print it in a list.

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs [hunk 10]
```diff
@@ -0,0 +1,99 @@
...
+                    subcommand: "sources",
+                    arguments: "root/sub",
+                    stdOut: out output,
+                    stdErr: out error,
+                    environment: environment,
+                    workingDir: projectPath);
+
+                Assert.Equal(0, exitCode);
+                Assert.Empty(error);
+                Assert.Contains(expectedContent, output);
```
Comment (troydai) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs]: Errrr, I don't feel good about this.

**Comment by troydai** [comment]
:watch:

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+
+            var sources = config.Sources.LoadPackageSources().ToList();
+            if (!sources.Any())
+            {
+                Reports.Information.WriteLine("No sources found.");
+            }
+            else
+            {
+                Reports.Information.WriteLine("Registered Sources:");
+                // Iterate over the sources and report them
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Nit: add empty line before comment

**Comment by BrennanConroy** [comment]
Fix tests!

**Comment by anurse** [comment]
I'm going to rename this to `list-sources` for now to unblock. I'll also go through the CI failures and remaining code review feedback.

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs (hunk 9 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: I'm mostly trying to mirror the existing `nuget sources` command, but I'm open to changing it. I'll remove the table formatting for now, we can always tweak it later.

File: src/Microsoft.Framework.PackageManager/NuGetConfig.cs (hunk 6 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/NuGetConfig.cs]: Sure, it's just moved from the old code so I wasn't sure if it was being left in for a reason.

File: src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs (hunk 7 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Restore/RestoreCommand.cs]: Just trying not to rock the boat too much and leave the code as it was before. I can do that though.

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs (hunk 8 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Probably not, I just need to add a counter. I copied this from `nuget sources` so between this and the below comment I'll probably just rework this a bit in general and I'll cover this comment there.

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs (hunk 10 above)
Comment (anurse) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs]: Yeah, I'm trying to find a balance between a brittle test and testing the actual functionality. I think I can put the whole of the expected output here, but from experience that can lead to a lot of tests breaking from a small change :). Here, I think it'll be fine, at least until we deal with localization :P

**Comment by anurse** [comment]
Ping @troydai @BrennanConroy @victorhurdugaci - Updated to resolve feedback.

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs [hunk 12]
```diff
@@ -0,0 +1,42 @@
+﻿// Copyright (c) .NET Foundation. All rights reserved.
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System.Linq;
+
+namespace Microsoft.Framework.PackageManager
+{
+    internal class ListSourcesCommand
+    {
+        public Reports Reports { get; set; }
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: This seems to be required and if it null it will fail. Why don't you pass it as a constructor arg ?

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+        public string TargetDirectory { get; set; }
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Same as above

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs [hunk 14]
```diff
@@ -0,0 +1,154 @@
...
+    'root': {
+        'NuGet.Config': """",
+        'sub': {
+            'NuGet.Config': """"
+        }
+    }
+}";
+
+            var expectedContent = @"Registered Sources:
+1.  Source1 https://source1 [Disabled]
```
Comment (victorhurdugaci) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs]: Is the order deterministic?

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs (hunk 12 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Just because everything else did it this way :). I'll fix this one

File: src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs (hunk 13 above)
Comment (anurse) [inline src/Microsoft.Framework.PackageManager/Sources/ListSourcesCommand.cs]: Same as above :)

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs (hunk 14 above)
Comment (anurse) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuSourcesTests.cs]: Generally, yes. I do intentionally clear the machine level sources so that should make it deterministic. Changes to our package source code could adjust this order, but those should cause the tests to fail anyway.

**Comment by anurse** [comment]
Ping @victorhurdugaci again :)

**Comment by troydai** [comment]
My concerns are addressed. :shipit:

**Comment by anurse** [comment]
I can't figure out what's wrong with the PR builds. I'm going to give a private TeamCity build a quick shot and if that doesn't work, just YOLO push and be prepared to revert :).
