### PR TITLE
Fix for publishing issue with RIDs

### LINKED ISSUE #3183: dnu publish does not honor RIDs
When using `dnu publish`, we do not scan the correct section in the lock file and as a result we miss most of the `runtime.[rid].[assemblyname]` packages. This causes problems with runtime-specific packages that are not embedded in DNX (for example `System.Data.SqlClient` and `System.Net.Security`)

/cc @DamianEdwards @muratg @Eilon

### PR DESCRIPTION
**Pull request by anurse**
This is a candidate fix for the publishing issue with RIDs. I verified that it fixes the problem in my repro. I still need to go through it and tidy it up a bit though.

fixes #3183

/cc @davidfowl @muratg @ericstj @DamianEdwards @danroth27 @Eilon

### CODE REVIEW

File: misc/PublishRuntimeDependency/Program.cs [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+            using (var stream = GetStream(socket, url))
+            {
+                // Send the request
+                var request = $"GET {url.PathAndQuery} HTTP/1.1\r\nHost: {url.Host}\r\nConnection: close\r\n\r\n";
+                var buffer = Encoding.UTF8.GetBytes(request);
+                stream.Write(buffer, 0, buffer.Length);
+
+                // Read the response
+                byte[] readbuffer = new byte[1024];
```
Comment (moozzyk) [inline misc/PublishRuntimeDependency/Program.cs]: Can you just use `StreaemReader.ReadToEnd` here?

Comment (anurse) [inline misc/PublishRuntimeDependency/Program.cs]: This code was actually taken from a different test which was trying to repro a bug in System.Net.Security around StreamReader.ReadToEnd :). I can trim it back since we don't care about that here.

**Comment by moozzyk** [comment]
LGTM
