### PR TITLE
Fix #876, Correct handling of quotation marks in commands

### LINKED ISSUE #876: Script blocks with spaces in arguments will fail.
ScriptExecutor will remove the quotes in script block unconditionally, as a result user can't wrap argument in quotes.

### PR DESCRIPTION
**Pull request by dougbu**
- don't strip quotes surrounding command-line arguments when used in `scripts`
 - prevented command paths and grouping arguments containing spaces
 - pass `preserveSurroundingQuotes` into `CommandGrammar` to control stripping
- support expected shell capabilities such as quoting command and redirections
 - use `cmd /s /c` when executing `scripts` on Windows
 - use `/bin/bash -c` when executing `scripts` on Linux
- add functional tests of commands and scripts (together with `dnu restore`)
 - no `dnu restore` for .NET Core due to extra time required

note:
- `CommandGrammar` may need additional generalizations
 - e.g. unquoted term can't contain more than one escape sequence
 - but it's probably good enough for now
- _not_ adding quotes around variables replacements inserted into commands
 - no way of determining if replacement is already quoted
 - basically, leave it to project.json author to perform appropriate quoting for their platform

nits:
- ~~let VS do its thing with test services~~
- make `CommandGrammar` constructor private; used only in `Process()` method
- update a few `ScriptExecutor` comments, long lines, et cetera

### CODE REVIEW

**Comment by dougbu** [comment]
/cc @davidfowl 

Any suggestions on unit / integration / functional testing of scripts? I don't see anything in this repo at the moment.

**Comment by dougbu** [comment]
@davidfowl since you like to look at individual commits, I rebased and added a couple more :smiley_cat: 

Latest version is more resilient and I've tested it numerous ways -- manually. (Don't seem to have test infrastructure in place to automated anything here.)

**Comment by dougbu** [comment]
Rebased again and added tests.

@davidfowl this bug is for Beta 5.

**Comment by davidfowl** [comment]
@dougbu This is broken on *nix. Look at travis

File: test/Microsoft.Framework.PackageManager.FunctionalTests/DnuRestoreTests.cs [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+        {
+            get
+            {
+                return TestUtils.GetRuntimeComponentsCombinations();
+            }
+        }
+
+        [ConditionalTheory]
+        [MemberData(nameof(RuntimeComponents))]
+        [OSSkipCondition(OperatingSystems.Linux | OperatingSystems.MacOSX)]
```
Comment (BrennanConroy) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuRestoreTests.cs]: Why?

Comment (dougbu) [inline test/Microsoft.Framework.PackageManager.FunctionalTests/DnuRestoreTests.cs]: Because i am positive my `bash`-writing skills are out-of-date and don't have a Linux system to play on. We can follow-up later with additional scripts.

**Comment by dougbu** [comment]
@davidfowl Travis builds now successful because all new tests are disabled on Mac and Linux. AppVeyor build queued; no idea when it will start but local `verify` builds are fine.

**Comment by dougbu** [comment]
Should have mentioned: No regressions on Mac or Linux i.e. I disabled only my new tests there.

File: test/Microsoft.Framework.ApplicationHost.FunctionalTests/AppHostTests.cs [hunk 2]
```diff
@@ -170,5 +171,131 @@ public void AppHostShowsErrorWhenCurrentTargetFrameworkWasNotFoundInProjectJson(
...
+                string error;
+                exitCode = BootstrapperTestUtils.ExecBootstrapper(
+                    runtimeHomePath,
+                    arguments: $@"""{ projectPath }"" { command } extra",
+                    stdOut: out output,
+                    stdErr: out error);
+
+                Assert.Equal(0, exitCode);
+                Assert.Empty(error);
+                Assert.Equal(expectedOutput, output);
```
Comment (ChengTian) [inline test/Microsoft.Framework.ApplicationHost.FunctionalTests/AppHostTests.cs]: `DNX_TRACE` is turned on by default in our TeamCity CI and you'll get extra info in output.

Use `Assert.Contains()` or turn off `DNX_TRACE` in the subprocess with something like:
https://github.com/aspnet/dnx/blob/dev/test/Bootstrapper.FunctionalTests/BootstrapperTests.cs#L114

Comment (dougbu) [inline test/Microsoft.Framework.ApplicationHost.FunctionalTests/AppHostTests.cs]: :ok: I turned off `DNX_TRACE` for other added tests in this PR. Will do the same here.

File: src/Microsoft.Framework.Runtime.Sources/Impl/EntryPointExecutor.cs [hunk 3]
```diff
@@ -33,6 +33,17 @@ public static Task<int> Execute(Assembly assembly, string[] args, IServiceProvid
...
+                    {
+                        var arg = args[index];
+                        if (arg.StartsWith("\"", StringComparison.Ordinal) &&
+                            arg.EndsWith("\"", StringComparison.Ordinal))
+                        {
+                            // Remove quotes around this argument.
+                            args[index] = arg.Substring(1, arg.Length - 2);
+                        }
+                    }
+
```
Comment (dougbu) [inline src/Microsoft.Framework.Runtime.Sources/Impl/EntryPointExecutor.cs]: As @davidfowl and I discussed, will undo this change.

File: src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs [hunk 4]
```diff
@@ -29,7 +29,9 @@ public CommandGrammar(Func<string, string> variable)
 
             var unquotedTerm = Rep1(unquotedPiece.Or(specialPiece)).Str();
 
-            var quotedTerm = Ch('\"').And(Rep(quotedPiece.Or(specialPiece)).Str()).And(Ch('\"')).Left().Down();
+            var quotedTerm = Ch('\"').And(Rep(quotedPiece.Or(specialPiece)).Str()).And(Ch('\"'))
+                .Left().Down()
+                .Build(str => "\"" + str + "\"");
```
Comment (dougbu) [inline src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs]: As @davidfowl and I discussed offline, will make restoration of surrounding quotes conditional. Won't be done when parsing `commands` but will be for `scripts`.

File: src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs [hunk 5]
```diff
@@ -67,18 +71,44 @@ public bool Execute(Runtime.Project project, string scriptName, Func<string, str
...
+                        scriptArguments[0] = $"{ quote }{ prefix }{ scriptCandidate }{ quote }";
+                    }
+
+                    // Always use /bin/bash -c in order to support redirection and so on; similar to Windows case.
+                    // Unlike Windows, must escape quotation marks within the newly-quoted string.
+                    scriptArguments = new[] { "/bin/bash", "-c", "\"" }
+                        .Concat(scriptArguments.Select(argument => argument.Replace("\"", "\\\"")))
+                        .Concat(new[] { "\"" })
+                        .ToArray();
                 }
```
Comment (dougbu) [inline src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs]: /cc @troydai I fixed the problems in this `else` block that we discussed today. E.g. code no longer checks for the script file in whatever random directory `dnu` was executing.

File: src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs [hunk 6]
```diff
@@ -9,12 +9,12 @@ namespace Microsoft.Framework.ApplicationHost.Impl.Syntax
...
+        private CommandGrammar(Func<string, string> variable, bool preserveSurroundingQuotes)
         {
             var environmentVariablePiece = Ch('%').And(Rep(Ch().Not(Ch('%')))).And(Ch('%')).Left().Down().Str()
                 .Build(key => variable(key) ?? "%" + key + "%");
 
-            var escapeSequencePiece = 
+            var escapeSequencePiece =
                 Ch('%').And(Ch('%')).Build(_=>"%")
                     .Or(Ch('^').And(Ch('^')).Build(_ => "^"))
                     .Or(Ch('\\').And(Ch('\\')).Build(_ => "\\"))
```
Comment (dougbu) [inline src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs]: Didn't change `escapeSequencePiece` but it probably should not remove Windows (`'^'`) or Linux (`'\\'`) escapes when `preserveSurroundingQuotes`. Should be fine for now since double quotes are far more common than escaping a single character.

File: src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs [hunk 7]
```diff
@@ -30,6 +30,12 @@ public CommandGrammar(Func<string, string> variable)
             var unquotedTerm = Rep1(unquotedPiece.Or(specialPiece)).Str();
 
             var quotedTerm = Ch('\"').And(Rep(quotedPiece.Or(specialPiece)).Str()).And(Ch('\"')).Left().Down();
+            if (preserveSurroundingQuotes)
+            {
+                // Str() value assigned to quotedTerm does not include quotation marks surrounding the quoted or
+                // special piece. Add those quotes back if requested.
+                quotedTerm = quotedTerm.Build(str => "\"" + str + "\"");
+            }
```
Comment (dougbu) [inline src/Microsoft.Framework.ApplicationHost/Impl/Syntax/CommandGrammar.cs]: Also likely minor but `quotedTerm` will not keep a (Linux-only) single-quoted argument string together.

**Comment by dougbu** [comment]
@davidfowl rebased, updated, and working on Linux. (Not sure why the Travix-ci/pr build hung but the push build succeeded.)

File: src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs [hunk 8]
```diff
@@ -67,18 +71,44 @@ public bool Execute(Runtime.Project project, string scriptName, Func<string, str
...
                 else
                 {
-                    var scriptCandiate = scriptArguments[0] + ".sh";
-                    if (File.Exists(scriptCandiate))
+                    // Special-case a script name that, perhaps with added .sh, matches an existing file.
+                    var surroundWithQuotes = false;
+                    var scriptCandidate = scriptArguments[0];
+                    if (scriptCandidate.StartsWith("\"", StringComparison.Ordinal) &&
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs]: Can you have spaces before the first quote or after the last one?

File: src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs [hunk 9]
```diff
@@ -67,18 +71,44 @@ public bool Execute(Runtime.Project project, string scriptName, Func<string, str
...
-                        scriptArguments[0] = scriptCandiate;
-                        scriptArguments = new[] { "/bin/bash" }.Concat(scriptArguments).ToArray();
+                        scriptCandidate = scriptCandidate + ".sh";
                     }
+
+                    if (File.Exists(Path.Combine(project.ProjectDirectory, scriptCandidate)))
+                    {
+                        // scriptCandidate may be a path relative to the project root. If so, likely will not be found
+                        // in the $PATH; add ./ to let bash know where to look.
+                        var prefix = Path.IsPathRooted(scriptCandidate) ? string.Empty : "./";
```
Comment (victorhurdugaci) [inline src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs]: I don't think the path can be rooted  because of the if block above. The project directory + a rooted path will not result in a valid file name

File: src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs (hunk 8 above)
Comment (dougbu) [inline src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs]: That's possible in the project.json file. But `CommandGrammar` removes spaces between and before all arguments and ignores the (remote) possibility of an argument that contains more than a correctly-quoted string.

**Comment by victorhurdugaci** [comment]
Looks good to me and I only had the two comments above

File: src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs (hunk 9 above)
Comment (dougbu) [inline src/Microsoft.Framework.PackageManager/Scripts/ScriptExecutor.cs]: `Path.Combine()` returns the right-hand argument if it is rooted.

**Comment by victorhurdugaci** [comment]
:shipit:

**Comment by dougbu** [comment]
90f1f03
